# Generated by Django 5.0.3 on 2024-03-17 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Limits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Limit', models.CharField(default='Limit', max_length=10)),
                ('GuideLimit', models.IntegerField(default=2)),
                ('ChairPerson', models.IntegerField(default=5)),
                ('CommitteeLimit', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Report', models.FileField(upload_to='reports')),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('UnderReview', 'UnderReview')], default='Pending', max_length=50)),
                ('Evaluation', models.IntegerField(default=-1)),
                ('Evaluation_Comments', models.CharField(blank=True, default='', max_length=1000)),
                ('Report_Comments', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollNoId', models.CharField(max_length=9, unique=True)),
                ('projectname', models.CharField(default='Default', max_length=50)),
                ('Phase1', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_phase1', to='projects.phase')),
                ('Phase2', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_phase2', to='projects.phase')),
                ('Phase3', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_phase3', to='projects.phase')),
                ('chair_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chair_projects', to='faculty.faculty')),
                ('committee_members', models.ManyToManyField(blank=True, related_name='member_of', to='faculty.faculty')),
                ('domain_categories', models.ManyToManyField(blank=True, related_name='Domain', to='projects.domain')),
                ('guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guide_projects', to='faculty.faculty')),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student')),
            ],
        ),
    ]
