# Generated by Django 5.0.3 on 2024-03-17 05:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='limits',
            name='Phase1_end',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='limits',
            name='Phase1_start',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='limits',
            name='Phase2_end',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='limits',
            name='Phase2_start',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='limits',
            name='Phase3_end',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='limits',
            name='Phase3_start',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='project',
            name='sugg_chair',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='sugg_mem1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='sugg_mem2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
