# Generated by Django 5.0.3 on 2024-03-14 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_alter_faculty_user'),
        ('projects', '0002_alter_project_eval1comment_and_more'),
        ('students', '0007_alter_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Report', models.FileField(upload_to='reports')),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('UnderReview', 'UnderReview')], default='Pending', max_length=50)),
                ('Evaluation', models.IntegerField(default=-1)),
                ('Evaluation_Comments', models.CharField(blank=True, default='', max_length=1000)),
                ('Report_Comments', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='eval1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='eval1comment',
        ),
        migrations.RemoveField(
            model_name='project',
            name='eval2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='eval2comment',
        ),
        migrations.RemoveField(
            model_name='project',
            name='eval3',
        ),
        migrations.RemoveField(
            model_name='project',
            name='eval3comment',
        ),
        migrations.RemoveField(
            model_name='project',
            name='report1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='report1acceptancestatus',
        ),
        migrations.RemoveField(
            model_name='project',
            name='report1comment',
        ),
        migrations.RemoveField(
            model_name='project',
            name='report2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='report2acceptancestatus',
        ),
        migrations.RemoveField(
            model_name='project',
            name='report2comment',
        ),
        migrations.RemoveField(
            model_name='project',
            name='report3',
        ),
        migrations.RemoveField(
            model_name='project',
            name='report3acceptancestatus',
        ),
        migrations.RemoveField(
            model_name='project',
            name='report3comment',
        ),
        migrations.AlterField(
            model_name='project',
            name='chair_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chair_projects', to='faculty.faculty'),
        ),
        migrations.AlterField(
            model_name='project',
            name='committee_members',
            field=models.ManyToManyField(blank=True, related_name='member_of', to='faculty.faculty'),
        ),
        migrations.AlterField(
            model_name='project',
            name='guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guide_projects', to='faculty.faculty'),
        ),
        migrations.AlterField(
            model_name='project',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student'),
        ),
        migrations.AddField(
            model_name='project',
            name='Phase1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_phase1', to='projects.phase'),
        ),
        migrations.AddField(
            model_name='project',
            name='Phase2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_phase2', to='projects.phase'),
        ),
        migrations.AddField(
            model_name='project',
            name='Phase3',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_phase3', to='projects.phase'),
        ),
    ]
