# Generated by Django 5.0.3 on 2024-03-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_limits_phase1_end_limits_phase1_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='limits',
            name='Phase1_Max_Marks',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='limits',
            name='Phase2_Max_Marks',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='limits',
            name='Phase3_Max_Marks',
            field=models.IntegerField(default=40),
        ),
    ]
