# Generated by Django 5.0.3 on 2024-03-14 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_domain_project_domain_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='domain_name',
            new_name='domain_categories',
        ),
    ]
