# Generated by Django 5.0.3 on 2024-03-14 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rename_domain_name_project_domain_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Limits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Limit', models.CharField(default='Limit', max_length=10)),
                ('GuideLimit', models.IntegerField(default=2)),
                ('ChairPerson', models.IntegerField(default=5)),
                ('CommitteeLimit', models.IntegerField(default=5)),
            ],
        ),
    ]
