# Generated by Django 5.0.3 on 2024-03-17 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dept', models.CharField(max_length=255)),
                ('isguide', models.IntegerField(default=0)),
                ('ischair', models.IntegerField(default=0)),
                ('iscommem', models.IntegerField(default=0)),
                ('isprojcoo', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('domain', models.CharField(max_length=255)),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
